@Library("dsd-jenkins-k8s") _

deployProject (
    serviceName: "sonar-golang-demo",
    projectType: "go",
    customImage: "golang:1.14.4",
    testCommand: "export http_proxy=http://pkg.proxy.prod.jp.local:10080 && export https_proxy=http://pkg.proxy.prod.jp.local:10080 && go test -coverprofile=coverage.out -json > test-report.json",
    sonarQubeName: "SonarQubeDemo",
    skipBuild: "true",
    skipDockerBuild: "true",
    skipDockerPush: "true",
    skipDeployment: "true",
    ignoreGitHeadMove: "true",
    targetEnv: "stg",
)