@Library("dsd-jenkins-k8s") _

deployProject (
    serviceName: "sonar-golang-demo",
    projectType: "go",
    customImage: "artifactory.rakuten-it.com/dsd-docker-dev-local/golang-dev:1.14.2-alpine3.11",
    testCommand: "export http_proxy=http://pkg.proxy.prod.jp.local:10080 && export https_proxy=http://pkg.proxy.prod.jp.local:10080 && go mod download && go test -coverprofile=coverage.out -json > test-report.json",
    sonarQubeName: "SonarQubeDemo",
    skipBuild: "true",
    skipDockerBuild: "true",
    skipDockerPush: "true",
    skipDeployment: "true",
    ignoreGitHeadMove: "true",
    targetEnv: "stg",
)